Add search option
canopas/compose-country-picker pull request #2
Opened 2022-04-06 09:00 UTC by cp-luzi-p

2022-04-06 09:07 UTC, cp-luzi-p commented
![Peek 2022-04-06 11-45](https://user-images.githubusercontent.com/76768856/161938520-1d3f3d2e-a909-416e-8bce-9cdebc859496.gif)

2022-04-09 03:55 UTC, cp-radhika-s commented on countrypicker/src/main/java/com/canopas/campose/countrypicker/CountrySearchView.kt
> +    } else if (searchValue.isNotEmpty()) {
`if (searchValue.isNotEmpty()` remove

2022-04-09 03:56 UTC, cp-radhika-s requested changes

2022-04-09 03:56 UTC, cp-radhika-s commented on countrypicker/src/main/java/com/canopas/campose/countrypicker/CountryPickerBottomSheet.kt
> +    dialogSearch: Boolean = true,
What is use of `dialogSearch ` flag?

2022-04-09 05:37 UTC, cp-hardik-p reviewed
Can we use string resources here?

2022-04-09 05:38 UTC, cp-luzi-p commented
> Can we use string resources here?

yes

2022-04-09 05:51 UTC, cp-megh-l approved these changes

2022-04-09 05:56 UTC, cp-hardik-p approved these changes

2022-04-09 05:56 UTC, cp-hardik-p commented on app/src/main/java/com/canopas/campose/jetcountypicker/MainActivity.kt
>                  label = "Select country",
Can we use string resources here?

2022-04-09 05:56 UTC, cp-hardik-p commented on countrypicker/src/main/java/com/canopas/campose/countrypicker/CountrySearchView.kt
> +                    text = "Search",
Can we use string resources here?

2022-04-09 05:56 UTC, cp-hardik-p commented on countrypicker/src/main/java/com/canopas/campose/countrypicker/CountryPickerBottomSheet.kt
> +                                    .padding(start = 6.dp)
Add padding in multiples of 4

2022-04-09 05:56 UTC, cp-hardik-p commented on countrypicker/src/main/java/com/canopas/campose/countrypicker/CountryPickerBottomSheet.kt
> +                                    .padding(start = 6.dp)
Same as above

2022-04-09 06:39 UTC, cp-radhika-s approved these changes

2022-04-09 06:40 UTC, merged